name: 'Docker Development Image'

on:
  workflow_dispatch:
    inputs:
      php:
        description: 'PHP Version'
        required: true
        default: '8.2.5'
      zts:
        description: 'ZTS (Zend Thread Safety)'
        required: true
        default: 'no'
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push API
        id: docker_build_zts
        uses: docker/build-push-action@v2
        if: ${{ github.event.inputs.zts == 'yes' }}
        with:
          file: Dockerfile
          context: .
          push: true
          pull: truez
          platforms: linux/amd64
          target: base
          tags: ${{ secrets.DOCKER_USERNAME }}/scylladb-php-driver:php-${{ github.event.inputs.php }}-zts
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            PHP_VERSION=${{ github.event.inputs.php }}
            PHP_ZTS=${{ github.event.inputs.zts }}
            PHP_DEBUG="no"
      - name: Build and push API
        id: docker_build_nts
        uses: docker/build-push-action@v2
        if: ${{ github.event.inputs.zts == 'no' }}
        with:
          file: Dockerfile
          context: .
          push: true
          pull: truez
          platforms: linux/amd64
          target: base
          tags: ${{ secrets.DOCKER_USERNAME }}/scylladb-php-driver:php-${{ github.event.inputs.php }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            PHP_VERSION=${{ github.event.inputs.php }}
            PHP_ZTS=${{ github.event.inputs.zts }}
            PHP_DEBUG="no"